### ISSUE TITLE
Publish test coverage

### ISSUE THREAD

**Issue by Nigui** [unik-name/uns-cli#5]
> > > Do we publish code coverage ?
> > 
> > 
> > Nice catch, we should
> 
> With @oclif/test we don't have coverage directly like other jest tests

Why to use `@oclif/test` then ? Without `@oclif/test` it looks like that https://blog.martianwabbit.com/2018/05/25/testing-oclif-with-jest.html

_Originally posted by @Nigui in https://github.com/unik-name/uns-cli/pull/2#issuecomment-537827124_

**Comment by dlecan** [comment]
Will be covered by https://spacelephant.tpondemand.com/entity/1475 (internal tracker)
